# Generated by Django 5.2.4 on 2025-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('Name', models.CharField(max_length=120)),
                ('Username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
