# Generated by Django 5.2.4 on 2025-07-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Username',
            new_name='username',
        ),
    ]
