# Generated by Django 5.2.4 on 2025-07-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_login_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Register',
        ),
    ]
