# Generated by Django 5.2.4 on 2025-07-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_login_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('caller_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=10)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register')),
            ],
        ),
    ]
