# Generated by Django 5.2.4 on 2025-07-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_callrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='caller_number',
        ),
        migrations.RemoveField(
            model_name='callrecording',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='callrecording',
            name='status',
        ),
    ]
