# Generated by Django 5.2.4 on 2025-07-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_callrecording_caller_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='call_date',
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='upload_date',
            field=models.DateTimeField(verbose_name='Date added'),
        ),
    ]
